### ISSUE TITLE
Allow roles as assignees

### ISSUE THREAD

**Issue by faranshahid** [swifty-report-cards/swifty-bot#12]
**Is your feature request related to a problem? Please describe.**
Yes. We have 14 clans with a lot of coleaders and leaders. I wanted them all to be able to use the bot but adding all of them as assignees is an arduous task. In addition, if we add a new coleader then we'll have to run the command for him again. Waste of time in my opinion.

**Describe the solution you'd like**
Two possible solutions come to mind.
1- allow everyone who can view the channel to be able to use the report command. That way its the responsibility of the server manager to restrict who can use the bot and who can't
2- allow roles to be added as assignees. That way you can just do !add-assignees @Role and everyone having that role would be able to use the commands. Much simpler.

Both solutions are viable and can be implemented. If you can add both features that would be great as well.
```

**Comment by WebDeg-Brian** [comment]
Will add this to the road map. Thanks!

**Comment by WebDeg-Brian** [comment]
@faranshahid Added support for it
