### ISSUE TITLE
Risk of Kick

### ISSUE THREAD

**Issue by csimpson11** [swifty-report-cards/swifty-bot#2]
**Describe the bug**
I have Risk of Kick set to 0 but it is still showing one member at Risk of Kick. When I had Risk of Kick set to 3, it was showing 4 at Risk of Kick.

**To Reproduce**
Just the the bottom n members to 0

**Expected behavior**
Show 0 members at Risk of Kick

**Screenshots**
![Annotation 2019-04-16 095316](https://user-images.githubusercontent.com/11131406/56220117-8143a680-602d-11e9-863a-77ed7aed7d04.jpg)

**Context**
- Bot version: [e.g v1.0.1]

**Comment by WebDeg-Brian** [comment]
@csimpson11 Could you please include the screenshot for bottom 4 members please?

**Comment by csimpson11** [comment]
![Annotation 2019-04-16 113020](https://user-images.githubusercontent.com/11131406/56227424-0d0fff80-603b-11e9-8e38-69e4c9e8f169.jpg)

**Comment by WebDeg-Brian** [comment]
Mind sending over the report if possible? @csimpson11

**Comment by csimpson11** [comment]
[3_Crown_N_Down_2R89V00G (14).xlsx](https://github.com/swifty-report-cards/swifty-bot/files/3086251/3_Crown_N_Down_2R89V00G.14.xlsx)

**Comment by WebDeg-Brian** [comment]
@csimpson11 Should be fixed in [this commit](https://github.com/swifty-report-cards/swifty-bot/commit/8db1e842bc7b1ca0142c63cab8d3c62223a2f2ea)
