### ISSUE TITLE
Add a column for Total Wars

### ISSUE THREAD

**Issue by csimpson11** [swifty-report-cards/swifty-bot#3]
**Is your feature request related to a problem? Please describe.**
Yes. I want to know how many wars a member participated in

**Describe the solution you'd like**
Add a column for Total Wars so you can see how many wars that person has participated in.

**Describe alternatives you've considered**
Looking it up on RoyaleAPI.

**Additional context**
N/A

**Comment by WebDeg-Brian** [comment]
Nice idea. I will definitely add it to the roadmap
